pipeline {
    agent any
    tools {
        maven 'maven'
    }
    stages {
        stage('Checkout') {
            steps {
                dir('./starter') {
                    checkout scm

                }
            }
        }
        stage('Build') {
            steps {
                dir('./starter'){
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                 dir('./starter'){
                    sh 'mvn -B test'
                 }
                
            }
            post {
                always {
                    junit 'target/surfire-reports/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}
